### ISSUE TITLE
k2cli tools kubectl error

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#92] opened 2017-06-15 01:12 UTC
I'm getting an unintelligible error attempting to use `k2cli tools`
```
$ k2cli tool kubectl --config /home/jjulian/dev/cnct/rc/staging-cluster/config.yaml get namespaces 
Using K2 config file: /home/jjulian/dev/cnct/rc/staging-cluster/config.yaml
error: group map[:0xc8203bee00 authorization.k8s.io:0xc8203bf030 autoscaling:0xc8203bf0a0 batch:0xc8203bf260 rbac.authorization.k8s.io:0xc8204fc0e0 storage.k8s.io:0xc8204fc150 federation:0xc8203be930 apps:0xc8203bee70 authentication.k8s.io:0xc8203beee0 certificates.k8s.io:0xc8203bf2d0 componentconfig:0xc8203bf340 extensions:0xc8204fc000 policy:0xc8204fc070] is already registered
error: group map[:0xc8203bee00 authorization.k8s.io:0xc8203bf030 autoscaling:0xc8203bf0a0 batch:0xc8203bf260 rbac.authorization.k8s.io:0xc8204fc0e0 storage.k8s.io:0xc8204fc150 federation:0xc8203be930 apps:0xc8203bee70 authentication.k8s.io:0xc8203beee0 certificates.k8s.io:0xc8203bf2d0 componentconfig:0xc8203bf340 extensions:0xc8204fc000 policy:0xc8204fc070] is already registered
```
The same command using kubectl 1.6.4 works:
```
$ sudo kubectl --kubeconfig ~/.kraken/staging/admin.kubeconfig get namespaces
NAME              STATUS    AGE
default           Active    11m
kube-auth         Active    8m
kube-networking   Active    8m
kube-public       Active    11m
kube-system       Active    11m
```

**Comment by davidewatson** [comment] 2017-06-15 01:19
Is it possible that `--config` is being passed to kubectl instead of interpreted by k2cli? I.e. what happens if you try `k2cli tool --config ~/.kraken/config.yaml kubectl get namespaces`?

**Comment by joejulian** [comment] 2017-06-15 01:23
No luck. I tried moving it there and before tool. Always get the same error.

**Comment by davidewatson** [comment] 2017-06-15 01:23
Nack, it works both ways.

**Comment by joejulian** [comment] 2017-06-15 01:25
If it's working for you, then it may have something to do with oidc maybe.

**Comment by joejulian** [comment] 2017-06-15 01:28
It could also be a yaml parse failure. I created (and referenced) new anchors while leaving the defaults behind:
```
   - &defaultKeyPair
      name: defaultKeyPair
      kind: keyPair
      publickeyFile: "$HOME/.ssh/id_rsa.pub"
      privatekeyFile: "$HOME/.ssh/id_rsa"
   - &stagingKeyPair
      name: stagingKeyPair
      kind: keyPair
      publickeyFile: "/home/jjulian/dev/cnct/rc/staging-cluster/aws_staging.rsa.pub"
      privatekeyFile: "/home/jjulian/dev/cnct/rc/staging-cluster/aws_staging.rsa"
```

**Comment by alejandroEsc** [comment] 2017-06-15 14:34
I have seen that issue when either configuration is wrong/cert is wrong, or you arent authorized. I have a question. I never understood `k2cli tools kubectl --config` does this update your kubectl with the config you point it to?

**Comment by coffeepac** [comment] 2017-06-15 17:44
This error is typically due to using the wrong version of kubectl with kubernetes.  `k2cli tool kubectl` will use kubectl v1.4.x right now.  waiting on #86 to merge.  we will then need a release which I can do when that's merged.

**Comment by alejandroEsc** [comment] 2017-06-19 19:58
I can confirm @coffeepac, I think solution here is to create a kubectl-vm and allow users to select version, probably a scrip that creates a symbolic link to the version you want to use would help.

**Comment by coffeepac** [comment] 2017-06-19 21:17
@alejandroEsc the issue I linked will execute the outcome you want based on the K2 config file.  When #86 is closed you should try this again and make sure it works.

**Comment by coffeepac** [comment] 2017-06-28 20:32
this will work when kubectl tool works (find issue, put it here)

**Comment by coffeepac** [comment] 2017-07-26 21:52
fixed.

**Closed by coffeepac** 2017-07-26 21:52 UTC
Labels: bug, k2cli, priority-p3
