### ISSUE TITLE
Validate cluster-name

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#33] opened 2017-01-06 22:04 UTC
cluster name has a fixed character set that can be used and cannot be longer than 13 characters. Validate this field.

**Comment by coffeepac** [comment] 2017-01-11 21:19
might want to take a full review of k2 for where we need to filter other names

**Comment by coffeepac** [comment] 2017-04-19 20:18
blocked by k2recon

**Comment by coffeepac** [comment] 2017-06-07 22:30
duplicate of k2#321

**Closed by coffeepac** 2017-06-07 22:30 UTC
Labels: bug, help wanted, k2cli, priority-p1
