### ISSUE TITLE
Panic on `generate` when supplying an output filename

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2cli#129] opened 2017-08-13 06:48 UTC
In running generate by hand to compare latest config against my version in use, encountered the following error.

```
$ k2cli generate config.yaml.generated
config.yaml.generatedPulling image 'quay.io/samsung_cnct/k2:latest' ██████████ Complete
Error response from daemon: invalid bind mount spec ".:.": invalid volume specification: '.:.': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
panic: Error response from daemon: invalid bind mount spec ".:.": invalid volume specification: '.:.': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute

goroutine 1 [running]:
github.com/samsung-cnct/k2cli/cmd.containerAction(0xc4202c7b20, 0x1724040, 0xc4201eb140, 0xc4202d33b0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli/cmd/container_helpers.go:497 +0x3a3
github.com/samsung-cnct/k2cli/cmd.runFunc(0x175a5e0, 0xc420279240, 0x1, 0x1)
	/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli/cmd/generate.go:98 +0x2e1
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0x175a5e0, 0xc4202791c0, 0x1, 0x1, 0x175a5e0, 0xc4202791c0)
	/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1759f80, 0x100467c, 0xc420072058, 0x0)
	/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x1759f80, 0x0, 0x47)
	/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli/cmd/root.go:65 +0x31
main.main()
	/home/jjulian/.local/go/src/_/home/jjulian/dev/k2cli/main.go:23 +0x22
```

**Comment by sostheim** [comment] 2017-08-13 06:49
Note that running simple `k2cli generate` without a target name succeeds.

**Comment by sostheim** [comment] 2017-08-13 06:49
```
$ k2cli version
1.0.7-stable+git.sha.d7454e05aab6b0a3078b660fb44497dfa25a853a
```

**Comment by coffeepac** [comment] 2017-08-14 16:24
This is a duplicate of another bug:  https://github.com/samsung-cnct/k2cli/issues/107

**Closed by coffeepac** 2017-08-14 16:24 UTC
Labels: bug, k2cli

**Comment by sostheim** [comment] 2017-08-15 01:50
@coffeepac - sorry for the overhead, forgot about my own issue.  thanks for closing this.
