### ISSUE TITLE
add k2cli cluster upgrade 

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2cli#70] opened 2017-04-18 22:44 UTC
now that k2 has master node upgrade functionality, users should be able to run `k2cli cluster upgrade` to fire off upgrade.sh

**Comment by coffeepac** [comment] 2017-04-19 04:25
I think this is a dupe of #6  Mostly because I think the easiest way to implement the changes to non-master nodePools will be to extend the work you did to target any nodePool by name instead of being set to the master pool

**Comment by coffeepac** [comment] 2017-04-19 20:21
blocked until all nodePools can be upgraded in k2

**Comment by guineveresaenger** [comment] 2017-06-22 16:40
PR: #98

**Closed** 2017-06-27 17:22 UTC
Labels: feature request, k2cli, node management, priority-p1
